apiVersion: cluster.open-cluster-management.io/v1beta1 
kind: Placement 
metadata: 
    name: guestbook-app-placement
    namespace: default
spec: 
    numberOfClusters: 2
    clusterSets: 
        - default
        - global
    predicates:
    - requiredClusterSelector:
        labelSelector:
            matchLabels:
                env: dev    