---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: <folder-in-repo> # optional
    apps.open-cluster-management.io/git-tag: <tag-in-repo> # optional
    apps.open-cluster-management.io/git-desired-commit: <commit-id-in-repo> # optional, takes precedence to git-tag
    apps.open-cluster-management.io/git-clone-depth: "20" # optional, mandatory when using git-desired-commit
    apps.open-cluster-management.io/reconcile-option: merge # optional can be replace/merge
    apps.open-cluster-management.io/reconcile-rate: medium # optional, can be off/low/medium/high
  name: helloworld-subscription
  namespace: helloworld-app
spec:
  channel: helloworld-chn/helloworld-channel
  placement:
    placementRef:
      kind: Placement
      name: helloworld-placement
